# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    bus_handlers:
        namespace: App\
        resource: '../src/*/Application/{Command,Query}/*Handler.php'
        tags:
            - { name: tactician.handler, typehints: true }

    console:
        namespace: App\
        resource: '../src/*/Infrastructure/Console/*Command.php'

    repos:
        namespace: App\
        resource: '../src/*/Infrastructure/Doctrine'

    domain_services:
        namespace: App\
        resource: '../src/*/Domain/Service'

    App\Vending\Domain\Repository\BalanceRepositoryInterface: '@App\Vending\Infrastructure\Doctrine\DoctrineBalanceRepository'
    App\Vending\Domain\Repository\ProductRepositoryInterface: '@App\Vending\Infrastructure\Doctrine\DoctrineProductRepository'
    App\Vending\Domain\Repository\AvailableCoinsRepositoryInterface: '@App\Vending\Infrastructure\Doctrine\DoctrineAvailableCoinsRepository'



